export const types = {
  TOGGLE_COMPLETED: "TOGGLE-COMPLETED",
  TOGGLE_DELETED: "TOGGLE-DELETED",
  ADD_TASK: "ADD-TASK",
  DELETE_TASK: "DELETE-TASK",
  INPUT_TEXT: "INPUT-TEXT",
  CLOSE_ALERT: "CLOSE-ALERT",
};
